[editor]
auto-pairs = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.select]
"p" =	"paste_clipboard_after"
"P" =	"paste_clipboard_before"
"y" =	"yank_to_clipboard"
"Y" =	"yank_main_selection_to_clipboard"
"R" =	"replace_selections_with_clipboard"
"c" = ["yank_to_clipboard", "change_selection_noyank"]
"d" = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.normal]
"p" =	"paste_clipboard_after"
"P" =	"paste_clipboard_before"
"y" =	"yank_to_clipboard"
"Y" =	"yank_main_selection_to_clipboard"
"R" =	"replace_selections_with_clipboard"
"c" = ["yank_to_clipboard", "change_selection_noyank"]
"d" = ["yank_to_clipboard", "delete_selection_noyank"]

[keys.normal.space]
";" = "toggle_comments"

[keys.normal.space.space]
"R" = ":reload-all"
"C" = ":config-reload"
"w" = ":toggle whitespace.render all none"
